### ISSUE TITLE
How do I get the bytes played by the audio instance per second?

### ISSUE THREAD

**Issue by LmanTW** [kmamal/node-sdl#19]

**Comment by kmamal** [comment]
@LmanTW Audio instances play/record bytes at a constant rate. It can be calculated with:

```
const {
  channels,
  frequency,
  bytesPerSample,
} = audioInstance

const framesPerSecond = frequency
const samplesPerSecond = framesPerSecond * channels
const bytesPerSecond = samplesPerSecond * bytesPerSample
```

or simply `frequency * channels * bytesPerSample`

**Comment by kmamal** [comment]
@LmanTW Since we're talking about audio anyway: I'm working on a new release (adding joystick and controller support) and there will be some breaking changes to how audio instances are opened. I have already pushed some stuff to master so you can check the new [sdl.audio.devices](https://github.com/kmamal/node-sdl#sdlaudiodevices), [sdl.audio.openDevice()](https://github.com/kmamal/node-sdl#sdlaudioopendevicedevice-options), and also how it looks like in an [example](https://github.com/kmamal/node-sdl/blob/master/examples/10-echo/index.js#L7). These changes will land in `v6.0.0`.

**Comment by LmanTW** [comment]
thx!
