### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by LmanTW** [kmamal/node-sdl#21]
/Users/lukelin/Desktop/Music Of Light/node_modules/@kmamal/sdl/src/javascript/audio/index.js:20
		return device.type === "recording"
		              ^

TypeError: Cannot read properties of undefined (reading 'type')
    at Object.openDevice (/Users/lukelin/Desktop/Music Of Light/node_modules/@kmamal/sdl/src/javascript/audio/index.js:20:17)
    at createAudioPlayer (/Users/lukelin/Desktop/Music Of Light/LightEngine/Functions/Audio.js:19:30)
    at CREATE.audioPlayer (/Users/lukelin/Desktop/Music Of Light/LightEngine/Functions/Game.js:179:5)
    at menu (/Users/lukelin/Desktop/Music Of Light/menu.js:31:27)
    at Object.callback (/Users/lukelin/Desktop/Music Of Light/start.js:76:11)
    
    System: MacOS 10.15.7
    Node-SDL Version: 0.6.0

**Comment by kmamal** [comment]
@LmanTW The `device` that you are passing to `openDevice(device)` is `undefined`. It looks like you updated to `v0.6.0` and have encountered the issue I mentioned in https://github.com/kmamal/node-sdl/issues/19#issuecomment-1319883996.

If your code looks like this:
```js
const device = sdl.audio.devices.find((x) => !x.recording)
sdl.audio.openDevice(device)
```

Then you must update it to look like this:
```js
const device = sdl.audio.devices.find((x) => x.type === 'playback')
sdl.audio.openDevice(device)
```

Or even better:
```js
sdl.audio.openDevice({ type: 'playback' } )
```

**Comment by LmanTW** [comment]
oh, cool!
(By the way, it is now impossible to play audio from other threads, which makes it a bit difficult for me to optimize)

**Comment by kmamal** [comment]
You can still use threads for __rendering__ the audio, but you will need to pass the data to the main thread so that sdl can use it. I have added an example that shows how this might be accomplished: https://github.com/kmamal/node-sdl/tree/master/examples/12-audio-thread. You can further optimize that example by using a [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) and [Atomics](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics) for the data transfer between threads.

**Comment by LmanTW** [comment]
oh, this is a good way!
thx you to help :D
