### ISSUE TITLE
Headless support?

### ISSUE THREAD

**Issue by shish** [kmamal/node-sdl#23]
I have an app where I'd like to run internal tests in github actions, where there is no display, but it seems that even _importing_ this module ends up calling `SDL_Init(SDL_VIDEO)` - is there any way to avoid that?

https://github.com/shish/rosettaboy/actions/runs/3652221531/jobs/6170355337
```
.../rosettaboy/js/node_modules/@kmamal/sdl/src/javascript/index.js:6
const info = Bindings.initialize()
                      ^
Error: SDL_Init(0) error: No available video device
```

**Comment by kmamal** [comment]
Thanks for the feedback. I didn't realize this might be a use case.

Try with `v0.6.3`. I've changed it so that the video and audio subsystems are only optionally initialized. You can import the module normally and only creating windows or opening audio devices should fail.

Let me know if it worked.

**Comment by shish** [comment]
That appears to work, thank you very much! :D
