### ISSUE TITLE
Why is the joystick guid not matching gamepadtool etc?

### ISSUE THREAD

**Issue by patroza** [kmamal/node-sdl#38]
I noticed this library shows different GUIDs than the https://generalarcade.com/gamepadtool/ and other sdl applications.
~I wonder if that's because this library uses `SDL_JoystickGetDeviceGUID` instead of `SDL_JoystickGetGUID`.
could you expose both?~ for my app to work I need to find the same guid as the other tools.

Xbox One elite 2 controller
this library:
`0300938d5e040000ff02000000007200`
gamepad tool:
`030000005e040000ff02000000007801`

**Comment by patroza** [comment]
what I found so far is that for my use case, im trying to match guide with yuzu.
they're resetting the crc part in the guid to 0. this makes my ps5 controller guid match properly.
and my xbox controller also, until the last 3 numbers; 7200 - 7801.
I can't for the life of me figure out why...

- yuzu (sdl **2.8**) and sdl2 gamepad **tool** (sdl**2.0.7**) : `030000005e040000000b000000007801`
- node-sdl (sdl **2.8** with crc set to 0), and sdl2 gamepad **mapper** (sdl **2.26.1**): `030000005e040000000b000000007200`

interestingly enough, for the ps5 dualsense pro wired it matches differently:
- yuzu (sdl **2.8**),  node-sdl (sdl **2.8** with crc set to 0): `030000004c050000f20d000000016800`
- sdl2 gamepad **mapper** (sdl **2.26.1**): `030072264c050000f20d000000016800` (crc not removed)
- sdl2 gamepad **tool** (sdl**2.0.7**): `030000004c050000f20d000000000000`

so I guess im mainly wondering why xbox is so different..

**Comment by patroza** [comment]
found it, 
```
        // Disable raw input. When enabled this setting causes SDL to die when a web applet opens
        SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");
```

sorry for barking up the wrong tree :)

**Comment by kmamal** [comment]
@patroza you type much faster than me :p I was about to post the following, wich might still be useful to to have in the future so here it is anyway:

You probably figured this out yourself (and that's why you crossed out that part) but `SDL_JoystickGetGUID` and `SDL_JoystickGetGUID` get their values from the same place so that can't be the issue.

SDL_GUID looks like this:

```
        /* This GUID fits the standard form:
         * 16-bit bus
         * 16-bit CRC16 of the joystick name (can be zero)
         * 16-bit vendor ID
         * 16-bit zero
         * 16-bit product ID
         * 16-bit zero
         * 16-bit version
         * 8-bit driver identifier ('h' for HIDAPI, 'x' for XInput, etc.)
         * 8-bit driver-dependent type info
         */
```

So the last 4 digits are different because they depend on what input driver you are using. 72 is 'r' (raw) and 78 is 'x' (x-input). You can set the SDL_JOYSTICK_RAWINPUT environment variable to override the default input driver. Whether you should do that depends on what you are building. Why do you need the exact GUID?

As a sode note: latest node-sdl is using SDL 2.26.1. You have it listed as 2.8 in your tests?

**Comment by patroza** [comment]
@kmamal thanks a lot. yea I got there too after a long hard road.
listed as 2.28 as thats what I updated the lib to, to see if the older version was my problem.

regarding why; I have 4 different controllers in different parts of my home, which I either direct connect via usb, or via bluetooth/wireless dongle, or virtually via Moonshine/SteamLink. it is rather bothersome to manually go into settings to pick the right controller, so I decided to scan for the latest gamepad added, and pick a relevant profile and update the guid accordingly.
so for yuzu to like my profile changes, the guid of the controller must be one it understands :)
