### ISSUE TITLE
some small questions

### ISSUE THREAD

**Issue by LmanTW** [kmamal/node-sdl#9]
~~Hi here I come again~~
I have some small questions:
1. The name of the window in the taskbar
The name of the window in the taskbar is always called "node", is there any way to change it?
2. Text input
Is there something like "text input" that will allow me to type in different languages?

**Comment by kmamal** [comment]
@LmanTW 

1. The name of the window in the taskbar should be the same as the window's title. Let me know if that doesn't work for you.

![Screenshot from 2022-09-12 15-54-50](https://user-images.githubusercontent.com/7921499/189659543-f3d5f15f-6eeb-40c1-86fd-8097be7eb0a7.png)

2. I'm afraid this library (or in fact SDL2 itself) doesn't cover any actual GUI components or widgets. It just gives you the bare-bones cross-platform essentials to make a window and get input events. You could look over at npm to see if there are any canvas gui libraries (meaning they draw a gui on a canvas) but I'm not sure how they would handle user input since the events are different between sdl and html. I am working on a library that would provide this functionality but it's far from done.

**Comment by LmanTW** [comment]
<img width="1440" alt="截圖 2022-09-13 上午8 13 51" src="https://user-images.githubusercontent.com/82919705/189780241-56f7ab10-3616-44d1-89b7-45daa53f9494.png">

System: MacOS 10.15.7

**Comment by kmamal** [comment]
I finally managed to get access to a mac to test this... You're right, it looks like it groups all the windows by the executable that created them. I also managed to get the same behavior on windows by changing my taskbar settings. I don't think there's any way around this behavior other than renaming the node executable itself, but if you manage to find something please let me know.

I will close this issue for now.
